use std::{
    collections::BTreeSet,
    fs,
    io::Read,
    path::{Path, PathBuf},
};

use sha2::{Digest, Sha256};

const PACKAGED_SOURCE_ROOTS: &[&str] = &["../../plugins", "../../providers", "../../wandao_core"];
const BUNDLED_PLUGIN_IDS: &[&str] = &[
    "aliyun_thoughts",
    "dingtalk",
    "feishu",
    "ima",
    "notion",
    "obsidian",
    "onenote",
    "wiz",
    "wps",
    "xiliu",
    "yinxiang",
    "youdao",
    "yuque",
    "zsxq",
];

fn is_python_cache_directory_name(name: &std::ffi::OsStr) -> bool {
    name.to_string_lossy().eq_ignore_ascii_case("__pycache__")
}

fn collect_plugin_files(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut pending = vec![root.to_path_buf()];
    let mut files = Vec::new();
    while let Some(directory) = pending.pop() {
        let mut entries: Vec<_> = fs::read_dir(&directory)
            .map_err(|error| format!("failed to inspect {}: {error}", directory.display()))?
            .collect::<Result<_, _>>()
            .map_err(|error| format!("failed to inspect {}: {error}", directory.display()))?;
        entries.sort_by_key(|entry| entry.file_name());
        for entry in entries {
            let path = entry.path();
            let file_type = fs::symlink_metadata(&path)
                .map_err(|error| format!("failed to inspect {}: {error}", path.display()))?
                .file_type();
            if file_type.is_symlink() {
                return Err(format!(
                    "bundled plugin resources must not contain symlinks: {}",
                    path.display()
                ));
            }
            if file_type.is_dir() {
                if !is_python_cache_directory_name(&entry.file_name()) {
                    pending.push(path);
                }
                continue;
            }
            if !file_type.is_file() {
                return Err(format!(
                    "bundled plugin resource is not a regular file: {}",
                    path.display()
                ));
            }
            let lowercase = entry.file_name().to_string_lossy().to_ascii_lowercase();
            if lowercase.ends_with(".pyc") || lowercase.ends_with(".pyo") {
                continue;
            }
            files.push(path);
        }
    }
    files.sort();
    Ok(files)
}

fn sha256_file(path: &Path) -> Result<String, String> {
    let mut file = fs::File::open(path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    let mut digest = Sha256::new();
    let mut buffer = [0_u8; 64 * 1024];
    loop {
        let read = file
            .read(&mut buffer)
            .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
        if read == 0 {
            break;
        }
        digest.update(&buffer[..read]);
    }
    Ok(format!("{:x}", digest.finalize()))
}

fn generate_bundled_plugin_hashes(manifest_dir: &Path) -> Result<(), String> {
    let plugins_root = manifest_dir.join("../../plugins");
    let expected: BTreeSet<&str> = BUNDLED_PLUGIN_IDS.iter().copied().collect();
    let discovered: BTreeSet<String> = fs::read_dir(&plugins_root)
        .map_err(|error| format!("failed to inspect {}: {error}", plugins_root.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| format!("failed to inspect {}: {error}", plugins_root.display()))?
        .into_iter()
        .filter(|entry| {
            entry.file_type().is_ok_and(|kind| kind.is_dir())
                && entry.path().join("plugin.json").is_file()
        })
        .map(|entry| entry.file_name().to_string_lossy().to_string())
        .collect();
    let discovered_refs: BTreeSet<&str> = discovered.iter().map(String::as_str).collect();
    if discovered_refs != expected {
        return Err(format!(
            "bundled plugin set mismatch: expected {expected:?}, found {discovered_refs:?}"
        ));
    }

    let mut generated = String::from(
        "// @generated by build.rs; do not edit.\n\
         pub(crate) static BUNDLED_PLUGIN_HASHES: &[(&str, &str, &str)] = &[\n",
    );
    for plugin_id in BUNDLED_PLUGIN_IDS {
        let plugin_root = plugins_root.join(plugin_id);
        let files = collect_plugin_files(&plugin_root)?;
        if files.is_empty() || !plugin_root.join("plugin.json").is_file() {
            return Err(format!("bundled plugin {plugin_id} has no valid resources"));
        }
        for file in files {
            let relative = file
                .strip_prefix(&plugin_root)
                .map_err(|_| format!("plugin resource path escaped {}", plugin_root.display()))?;
            let relative = relative
                .components()
                .map(|component| component.as_os_str().to_str())
                .collect::<Option<Vec<_>>>()
                .ok_or_else(|| format!("plugin resource path is not UTF-8: {}", file.display()))?
                .join("/");
            let hash = sha256_file(&file)?;
            generated.push_str(&format!("    ({plugin_id:?}, {relative:?}, {hash:?}),\n"));
        }
    }
    generated.push_str("];\n");

    let output =
        PathBuf::from(std::env::var_os("OUT_DIR").ok_or_else(|| "OUT_DIR is not set".to_string())?)
            .join("bundled_plugin_hashes.rs");
    if fs::read_to_string(&output).ok().as_deref() != Some(generated.as_str()) {
        fs::write(&output, generated)
            .map_err(|error| format!("failed to write {}: {error}", output.display()))?;
    }
    Ok(())
}

struct RuntimeSpec {
    target: &'static str,
    interpreter: &'static str,
    asset: &'static str,
    archive_sha256: &'static str,
    python_version: &'static str,
    architecture: &'static str,
}

fn runtime_spec(rust_target: &str) -> Result<RuntimeSpec, String> {
    match rust_target {
        "x86_64-pc-windows-msvc" | "x86_64-pc-windows-gnu" | "x86_64-pc-windows-gnullvm" => {
            Ok(RuntimeSpec {
                target: "win-x64",
                interpreter: "python.exe",
                asset:
                    "cpython-3.11.15+20260623-x86_64-pc-windows-msvc-install_only_stripped.tar.gz",
                archive_sha256: "6589ca6d63f520bec4096d62b3ab91da3d0a80b16b594c99a6b677e335814683",
                python_version: "3.11.15",
                architecture: "x86_64",
            })
        }
        "x86_64-apple-darwin" => Ok(RuntimeSpec {
            target: "mac-x64",
            interpreter: "bin/python3",
            asset: "cpython-3.11.15+20260623-x86_64-apple-darwin-install_only_stripped.tar.gz",
            archive_sha256: "4925e5aaa9bc77c85302d350b36c1d9def2002996a6bcfa55c88ba6eb318de29",
            python_version: "3.11.15",
            architecture: "x86_64",
        }),
        "aarch64-apple-darwin" => Ok(RuntimeSpec {
            target: "mac-arm64",
            interpreter: "bin/python3",
            asset: "cpython-3.11.15+20260623-aarch64-apple-darwin-install_only_stripped.tar.gz",
            archive_sha256: "2318799eaf104f8a29bc09a93b0851b05dbbcb4ce9a5f045ddea169c0c7ff3a5",
            python_version: "3.11.15",
            architecture: "aarch64",
        }),
        _ => Err(format!(
            "release target {rust_target:?} has no supported bundled Python runtime"
        )),
    }
}

fn runtime_metadata_string<'a>(
    metadata: &'a serde_json::Value,
    field: &str,
) -> Result<&'a str, String> {
    metadata
        .get(field)
        .and_then(serde_json::Value::as_str)
        .filter(|value| !value.is_empty())
        .ok_or_else(|| format!("WANDAO_RUNTIME.json has an invalid {field} field"))
}

fn validate_runtime_tree(runtime: &Path) -> Result<(), String> {
    let runtime_type = fs::symlink_metadata(runtime)
        .map_err(|error| format!("failed to inspect {}: {error}", runtime.display()))?
        .file_type();
    if runtime_type.is_symlink() || !runtime_type.is_dir() {
        return Err(format!(
            "bundled runtime root must be a real directory: {}",
            runtime.display()
        ));
    }
    let canonical_root = fs::canonicalize(runtime)
        .map_err(|error| format!("failed to resolve {}: {error}", runtime.display()))?;
    let mut pending = vec![runtime.to_path_buf()];
    while let Some(directory) = pending.pop() {
        let entries = fs::read_dir(&directory)
            .map_err(|error| format!("failed to inspect {}: {error}", directory.display()))?;
        for entry in entries {
            let entry = entry.map_err(|error| {
                format!(
                    "failed to inspect an entry in {}: {error}",
                    directory.display()
                )
            })?;
            let path = entry.path();
            let file_type = fs::symlink_metadata(&path)
                .map_err(|error| format!("failed to inspect {}: {error}", path.display()))?
                .file_type();
            let relative = path
                .strip_prefix(runtime)
                .map_err(|_| format!("runtime path escaped {}", runtime.display()))?;
            let name = entry.file_name().to_string_lossy().to_ascii_lowercase();
            if name == "__pycache__" || name.ends_with(".pyc") || name.ends_with(".pyo") {
                return Err(format!(
                    "bundled runtime contains generated Python cache {}",
                    relative.display()
                ));
            }
            let in_site_packages = relative.components().any(|component| {
                component
                    .as_os_str()
                    .to_string_lossy()
                    .eq_ignore_ascii_case("site-packages")
            });
            let parent_is_scripts = relative.parent().is_some_and(|parent| {
                parent.file_name().is_some_and(|parent_name| {
                    let parent_name = parent_name.to_string_lossy();
                    parent_name.eq_ignore_ascii_case("scripts")
                        || parent_name.eq_ignore_ascii_case("bin")
                })
            });
            let build_tool_path = name == "ensurepip"
                || (in_site_packages
                    && (matches!(
                        name.as_str(),
                        "pip" | "setuptools" | "pkg_resources" | "_distutils_hack"
                    ) || (name.starts_with("pip-") && name.ends_with(".dist-info"))
                        || (name.starts_with("setuptools-") && name.ends_with(".dist-info"))))
                || name == "distutils-precedence.pth"
                || (parent_is_scripts
                    && (name.starts_with("pip") || name.starts_with("easy_install")));
            if build_tool_path {
                return Err(format!(
                    "bundled runtime contains build-only package tooling {}",
                    relative.display()
                ));
            }
            if file_type.is_symlink() {
                let target = fs::canonicalize(&path).map_err(|error| {
                    format!(
                        "bundled runtime has a broken symlink {}: {error}",
                        path.display()
                    )
                })?;
                if !target.starts_with(&canonical_root) {
                    return Err(format!(
                        "bundled runtime symlink escapes the runtime root: {} -> {}",
                        path.display(),
                        target.display()
                    ));
                }
                continue;
            }
            if file_type.is_dir() {
                pending.push(path);
            } else if !file_type.is_file() {
                return Err(format!(
                    "bundled runtime contains a non-regular resource {}",
                    relative.display()
                ));
            }
        }
    }
    Ok(())
}

fn validate_runtime(
    runtime: &Path,
    requirements: &Path,
    requirements_lock: &Path,
    rust_target: &str,
) -> Result<(), String> {
    let spec = runtime_spec(rust_target)?;
    let interpreter = runtime.join(spec.interpreter);
    if !interpreter.is_file() {
        return Err(format!(
            "release build requires bundled Python interpreter at {}",
            interpreter.display()
        ));
    }

    let metadata_path = runtime.join("WANDAO_RUNTIME.json");
    if !metadata_path.is_file() {
        return Err(format!(
            "release build requires runtime metadata at {}",
            metadata_path.display()
        ));
    }
    let metadata = std::fs::read_to_string(&metadata_path)
        .map_err(|error| format!("failed to read {}: {error}", metadata_path.display()))?;
    let metadata: serde_json::Value = serde_json::from_str(&metadata)
        .map_err(|error| format!("WANDAO_RUNTIME.json is not valid JSON: {error}"))?;
    if metadata
        .get("schemaVersion")
        .and_then(serde_json::Value::as_u64)
        != Some(1)
    {
        return Err("WANDAO_RUNTIME.json has an unsupported schemaVersion".to_string());
    }
    for (field, expected) in [
        ("target", spec.target),
        ("asset", spec.asset),
        ("archiveSha256", spec.archive_sha256),
        ("pythonImplementation", "CPython"),
        ("pythonVersion", spec.python_version),
        ("architecture", spec.architecture),
        (
            "preparedBy",
            "wandao_electron/scripts/prepare_python_runtime.py",
        ),
    ] {
        let actual = runtime_metadata_string(&metadata, field)?;
        if actual != expected {
            return Err(format!(
                "bundled Python metadata mismatch for {field}: expected {expected:?}, found {actual:?}"
            ));
        }
    }

    let requirements_sha256 = sha256_file(requirements)?;
    let prepared_requirements = runtime_metadata_string(&metadata, "requirementsSha256")?;
    if prepared_requirements != requirements_sha256 {
        return Err(format!(
            "bundled Python requirements mismatch: expected {requirements_sha256}, found {prepared_requirements}"
        ));
    }
    let requirements_lock_sha256 = sha256_file(requirements_lock)?;
    let prepared_requirements_lock = runtime_metadata_string(&metadata, "requirementsLockSha256")?;
    if prepared_requirements_lock != requirements_lock_sha256 {
        return Err(format!(
            "bundled Python requirements lock mismatch: expected {requirements_lock_sha256}, found {prepared_requirements_lock}"
        ));
    }
    let installed_packages = metadata
        .get("installedPackages")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "WANDAO_RUNTIME.json has an invalid installedPackages field".to_string())?;
    let installed_packages = installed_packages
        .iter()
        .map(|value| {
            value
                .as_str()
                .filter(|package| package.contains("=="))
                .ok_or_else(|| {
                    "WANDAO_RUNTIME.json has an invalid installedPackages entry".to_string()
                })
        })
        .collect::<Result<Vec<_>, _>>()?;
    if installed_packages.is_empty() || installed_packages.windows(2).any(|pair| pair[0] >= pair[1])
    {
        return Err(
            "WANDAO_RUNTIME.json installedPackages must be a sorted unique non-empty list"
                .to_string(),
        );
    }
    if !installed_packages
        .iter()
        .any(|package| package.eq_ignore_ascii_case("evernote-backup==1.13.1"))
    {
        return Err("bundled Python metadata does not include evernote-backup==1.13.1".to_string());
    }

    validate_runtime_tree(runtime)
}

fn first_packaged_source_cache(root: &Path) -> Result<Option<PathBuf>, String> {
    if !root.exists() && !root.is_symlink() {
        return Ok(None);
    }
    let root_type = fs::symlink_metadata(root)
        .map_err(|error| format!("failed to inspect {}: {error}", root.display()))?
        .file_type();
    if root_type.is_symlink() || !root_type.is_dir() {
        return Err(format!(
            "release resource root must be a real directory: {}",
            root.display()
        ));
    }

    let mut pending = vec![root.to_path_buf()];
    while let Some(directory) = pending.pop() {
        let entries = std::fs::read_dir(&directory)
            .map_err(|error| format!("failed to inspect {}: {error}", directory.display()))?;
        for entry in entries {
            let entry = entry.map_err(|error| {
                format!(
                    "failed to inspect an entry in {}: {error}",
                    directory.display()
                )
            })?;
            let path = entry.path();
            let name = entry.file_name();
            let lowercase_name = name.to_string_lossy().to_ascii_lowercase();
            if lowercase_name == "__pycache__"
                || lowercase_name.ends_with(".pyc")
                || lowercase_name.ends_with(".pyo")
            {
                return Ok(Some(path));
            }
            let file_type = entry
                .file_type()
                .map_err(|error| format!("failed to inspect {}: {error}", path.display()))?;
            if file_type.is_symlink() {
                return Err(format!(
                    "release resources must not contain symlinks: {}",
                    path.display()
                ));
            }
            if file_type.is_dir() {
                pending.push(path);
            } else if !file_type.is_file() {
                return Err(format!(
                    "release resource is not a regular file: {}",
                    path.display()
                ));
            }
        }
    }
    Ok(None)
}

fn validate_packaged_sources(manifest_dir: &Path) -> Result<(), String> {
    for relative_root in PACKAGED_SOURCE_ROOTS {
        let source_root = manifest_dir.join(relative_root);
        if let Some(cache) = first_packaged_source_cache(&source_root)? {
            return Err(format!(
                "release resources contain generated Python cache {}; run prepare_python_runtime.py before building",
                cache.display()
            ));
        }
    }
    Ok(())
}

fn main() {
    let manifest_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set"),
    );
    let python_runtime = manifest_dir.join("../runtime/python-runtime");
    let requirements = manifest_dir.join("../../requirements.txt");
    let requirements_lock = manifest_dir.join("../../requirements.lock");
    let profile = std::env::var("PROFILE").unwrap_or_default();

    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-env-changed=TARGET");
    println!("cargo:rerun-if-changed={}", python_runtime.display());
    println!("cargo:rerun-if-changed={}", requirements.display());
    println!("cargo:rerun-if-changed={}", requirements_lock.display());
    for relative_root in PACKAGED_SOURCE_ROOTS {
        println!(
            "cargo:rerun-if-changed={}",
            manifest_dir.join(relative_root).display()
        );
    }

    if profile == "release" {
        let rust_target = std::env::var("TARGET").expect("TARGET is not set for release build");
        validate_runtime(
            &python_runtime,
            &requirements,
            &requirements_lock,
            &rust_target,
        )
        .and_then(|_| validate_packaged_sources(&manifest_dir))
        .unwrap_or_else(|message| panic!("release resource validation failed: {message}"));
    } else {
        std::fs::create_dir_all(&python_runtime)
            .expect("failed to create placeholder Python runtime directory");
    }

    generate_bundled_plugin_hashes(&manifest_dir)
        .unwrap_or_else(|message| panic!("bundled plugin integrity generation failed: {message}"));

    tauri_build::build()
}
